[package]
name = "shell-watchdog"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
shell-core = { path = "../shell-core", version = "0.1.0" }
shell-diagnostics = { path = "../shell-diagnostics", version = "0.1.0" }

[lints]
workspace = true
