[package]
name = "shell-config"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shell-core = { path = "../shell-core", version = "0.1.0" }
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
